export const activityVisibleFieldsByModule = {
  agreements: [
    'agreement_id',
    'amount',
    'comments',
    'description',
    'email',
    'fullname',
    'installment_amount',
    'notes',
    'offer_id',
    'payment_method',
    'phone',
    'reference',
    'state_id',
    'street',
    'title',
  ],
  billings: [
    'amount',
    'billing_id',
    'comments',
    'description',
    'email',
    'payment_method',
    'reference',
    'state_id',
    'title',
  ],
  clients: [
    'fullname',
    'email',
    'client_type_name',
    'organization_number',
    'country_name',
    'num_iva',
    'phone',
    'landline',
    'address',
    'street',
    'postal_code',
    'reference',
    'comments',
  ],
  documents: [
    'comments',
    'description',
    'email',
    'notes',
    'phone',
    'reference',
    'state_id',
    'title',
  ],
  notes: [
    'comments',
    'description',
    'notes',
    'title',
  ],
  payouts: [
    'account',
    'amount',
    'comments',
    'description',
    'reference',
    'state_id',
    'title',
  ],
  vehicles: [
    'amount',
    'comments',
    'description',
    'notes',
    'num_iva',
    'payment_method',
    'reference',
    'reg_num',
    'state_id',
    'title',
  ],
}

export function getActivityVisibleFields(entityType) {
  return activityVisibleFieldsByModule[entityType] ?? null
}